# yaml-language-server: $schema=./changelog.schema.json


[[versions]]
version = "1.0.0"
versionCode = 1
date = "2082-02-22"
logs = [
    "Initial release of Mobile Banking application.",
    "Supports savings accounts overview, statements, and rate logs.",
    "Integrated scanner feature for secure QR payments.",
    "Enabled biometric fingerprint/Face ID authorization setup.",
    "Added biometric credential database change key invalidation and reset flow on iOS and Android.",
    "Added dynamic Face ID detection and icon changes for Apple devices."
]


[[versions]]
version = "1.0.1"
versionCode = 4
date = "2082-02-26"
logs = [
    "Some minor bugs fixes"
]
